name: koek-classify validate

on:
  push:
    paths:
    - koek-classify/**
  pull_request:
    paths:
    - koek-classify/**
  workflow_dispatch:

env: 
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: koek-classify

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose